Repository TraXpen-e/TraXpen-e-client, pull requests merged in 2021-12, with the labels that each got.

#2 Project migrated to Next.js
  .babelrc
  .env.example
  .eslintrc.json
  .gitignore
  README.MD
  next-i18next.config.js
  next.config.js
  package-lock.json
  package.json
  pages/[resource]/[action]/[id].tsx
  pages/[resource]/[action]/index.tsx
  pages/[resource]/index.tsx
  pages/_app.tsx
  pages/index.tsx
  public/favicon.ico
  public/images/flags/de.svg
  public/images/flags/en.svg
  public/locales/de/common.json
  public/locales/en/common.json
  public/vercel.svg
  src/components/layout/header/index.tsx
  src/components/layout/index.ts
  src/styles/global.css
  styles/Home.module.css
  styles/globals.css
  tsconfig.json
Labels: documentation

#4 Feature login form
  .babelrc
  .gitignore
  README.MD
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/signin.tsx
  pages/signup.tsx
  postcss.config.js
  src/components/Button.tsx
  src/components/Icons.tsx
  src/components/Input.tsx
  src/components/Signin.tsx
  src/components/Signup.tsx
  src/components/index.ts
  src/interfaces/index.ts
  styles/Home.module.css
  styles/globals.css
  styles/style.tsx
  tailwind.config.js
  tsconfig.json
Labels: enhancement, in progress

#7 JWT sign up
  .env.example
  .gitignore
  package-lock.json
  package.json
  pages/signin.tsx
  src/components/Errro.tsx
  src/components/Input.tsx
  src/components/Signup.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/usePostRequest.tsx
  src/interfaces/index.ts
  src/utils/axios.tsx
  src/utils/index.ts
  tsconfig.json
Labels: in progress

#11 [ET-7] User signin
  src/components/Button.tsx
  src/components/Signin.tsx
  src/components/Signup.tsx
  src/constants/index.ts
  src/hooks/usePostRequest.tsx
  src/interfaces/index.ts
  tsconfig.json
Labels: in progress

#13 [ET-11] landing page quality work section
  pages/home.tsx
  public/assets/images/hero-screenshot-1.png
  public/assets/images/team-illustration-1.svg
  src/components/HomePage/Features.tsx
  src/components/HomePage/QualityWork.tsx
  src/interfaces/index.ts
  styles/style.tsx
  tailwind.config.js
Labels: documentation

#15 [ET-12] Landing page features with steps
  pages/home.tsx
  public/assets/images/hero-screenshot-2.png
  src/components/HomePage/FeatureWithSteps.tsx
  src/components/HomePage/Features.tsx
  src/components/HomePage/Hero.tsx
  src/components/HomePage/QualityWork.tsx
  src/interfaces/index.ts
Labels: documentation

#17 [ET-13] landing page values
  package-lock.json
  package.json
  pages/_app.tsx
  pages/home.tsx
  public/assets/images/planning-illustration.svg
  src/components/HomePage/FeatureWithSteps.tsx
  src/components/HomePage/Features.tsx
  src/components/HomePage/Hero.tsx
  src/components/HomePage/QualityWork.tsx
  src/components/HomePage/Values.tsx
  src/interfaces/index.ts
  tailwind.config.js
Labels: documentation

#19 [ET-14] landing page pricing
  pages/_app.tsx
  pages/home.tsx
  public/assets/images/blob-3.svg
  src/components/HomePage/Pricing.tsx
  src/interfaces/index.ts
  styles/style.tsx
Labels: documentation
